spring:
  config:
    import: optional:configserver:http://config-service.fintech.svc.cluster.local:8889
  application:
    name: user-service
  web:
    resources:
      static-locations: file:./src/main/public/images/


image:
  folder:  src/main/public/images/



management:
  endpoints:
    web:
      exposure:
        include: "*"

