apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: fintech
data:
  application.yml: |-
    spring:
      application:
        name: user-service
      
      datasource:
        # Primary MySQL Database
        primary:
          url: jdbc:mysql://terraform-20250111154620029800000001.c122egeymo28.us-east-1.rds.amazonaws.com:3306/user_service_db
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            pool-name: MySQLPool
        
        # Secondary PostgreSQL Database
        secondary:
          url: jdbc:postgresql://postgres-instance.c122egeymo28.us-east-1.rds.amazonaws.com:5432/user_service_db
          driver-class-name: org.postgresql.Driver
          hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            pool-name: PostgresPool
      
      jpa:
        properties:
          hibernate:
            dialect:
              primary: org.hibernate.dialect.MySQLDialect
              secondary: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update
      
      config:
        import: optional:configserver:http://10.0.0.7:8889
      
      eureka:
        client:
          serviceUrl:
            defaultZone: http://10.0.1.37:8761/eureka/
          register-with-eureka: true
          fetch-registry: true
        instance:
          prefer-ip-address: true
      server:
        port: 8090
        management:
          endpoints:
            web:
              exposure:
                include: health,info,metrics,prometheus
          endpoint:
            health:
              show-details: when-authorized
              probes:
                enabled: true