apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: fintech
data:
  application.yml: |-
    spring:
      application:
        name: user-service
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update

      config:
        import: optional:configserver:http://config-service:8889
        
      server:
        port: 8090
        management:
          endpoints:
            web:
              exposure:
                include: health,info,metrics,prometheus
          endpoint:
            health:
              show-details: when-authorized
              probes:
                enabled: true