apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: user-service
data:
  application.yml: |-
    spring:
      application:
        name: user-service
      config:
        import: optional:configserver:http://config-server:8889
      web:
        resources:
          static-locations: file:/app/src/main/public/images/
    
    image:
      folder: /app/src/main/public/images/

    eureka:
      client:
        serviceUrl:
          defaultZone: http://discovery-service:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
      instance:
        prefer-ip-address: true