apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deploy
  namespace: fintech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: public.ecr.aws/z1z0w2y6/user-service:latest
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: user-service-config
          env:
            - name: SPRING_DATASOURCE_PRIMARY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: SPRING_DATASOURCE_PRIMARY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
            # PostgreSQL Credentials
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-instance.c122egeymo28.us-east-1.rds.amazonaws.com:5432/user_service_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 10